### ISSUE TITLE
Question: Work across requests

### ISSUE THREAD

**Issue by darrenhaken** [wsargent/circuit_breaker#12]
For a web application does this work across multiple HTTP requests or only circuit break within the scope of the request lifecycle?

**Comment by wsargent** [comment]
Depends on the lifecycle where you put the circuit breaker.  It's not specific to http applications.

**Comment by darrenhaken** [comment]
Can you give an example of using it in a web system and it not being request bound?

Sorry I hadn't replied sooner but I'll be better at getting back to you now, I've been on vacation!

**Comment by wsargent** [comment]
I don't understand what you mean.  The circuit breaker doesn't have any dependencies on a web application at all.  If you don't want it request bound, don't bind it to a request's lifecycle.

**Comment by darrenhaken** [comment]
The use case I was looking at was persisting the circuit breaker across requests so that once it's triggered further requests won't even try the external service once it's down (for a given time period).

Looking at the Gem again it looks like I'd just write this around it so I think I'm OK.
